version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: blotter-postgres-dev
    environment:
      POSTGRES_USER: blotter_user
      POSTGRES_PASSWORD: blotter_pass
      POSTGRES_DB: blotter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
